tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'homebrew/core'
cask 'java'
brew 'git'
brew 'gradle'
brew 'jq'
brew 'openssl'
brew 'maven'
brew 'reattach-to-user-namespace', args: ['with-wrap-pbcopy-and-pbpaste']
brew 'tmux'
brew 'tree'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'homebrew/completions/docker-completion'
